#! /bin/dash

# ==============================================================================
# tigger-add.sh
# Implementation of tigger-add command.
#
# Add files to staging area
#
# Written by: Kristine Jin <z5362038@ad.unsw.edu.au>
# Date: 3/07/2022
# For COMP2041 Assignment 1
# ==============================================================================

# Error checking
# tigger-add: error: tigger repository directory .tigger not found
if [ ! -d ".tigger" ]
then
    echo "tigger-add: error: tigger repository directory .tigger not found" 1>&2
    exit 1
fi 

if [ $# -eq 0 ]
then
    echo "usage: tigger-add <filenames>" 1>&2
    exit 1
fi

branch="$(cat .tigger/HEAD)"
index=.tigger/branches/"$branch"/index
for f in "$@"
do 
    if [ ! -f "$f" ]
    then
        if [ -f "$index"/"$f" ]
        then
            rm "$index"/"$f"
        else
            echo "tigger-add: error: can not open '$f'" 1>&2
            exit 1
        fi
    else
        cp "$f" .tigger/branches/"$branch"/index
    fi
done