#! /bin/dash

# add files to index
# only ordinary file can be added

# Error checking
# tigger-add: error: tigger repository directory .tigger not found
if [ ! -d ".tigger" ]
then
    echo "$0: error: tigger repository directory .tigger not found" 1>&2
    exit 1
fi 

# tigger-add: error: can not open 'b'
branch="$(cat .tigger/HEAD)"
for f in "$@"
do 
    if [ ! -f "$f" ]
    then
        echo "$0: error: can not open '$f'" 1>&2
        exit 1
    fi
    cp "$f" .tigger/branches/"$branch"/index
done

