#! /bin/dash

dirName=".tigger"

ls=$(ls -d $dirName 2>/dev/null)

if [ $? -eq 0 ]
then
    echo "$0: error: $dirName already exists"
    exit 0
fi 

mkdir $dirName

echo "Initialized empty tigger repository in $dirName"