#! /bin/dash

dirName=".tigger"

ls=$(ls -d $dirName 2>/dev/null)

if [ $? -eq 0 ]
then
    echo "$0: error: $dirName already exists" 1>&2
    exit 1
fi 

initbranch="master"

# create .tigger directory
mkdir $dirName
# create branches directory inside .tigger
mkdir $dirName/branches
# create main repo
mkdir $dirName/repo
# create directory for master
mkdir $dirName/branches/$initbranch
# set HEAD to master
echo "$initbranch" > $dirName/HEAD
# create index directory for master branch
mkdir $dirName/branches/$initbranch/index
# finish initialisation 
echo "Initialized empty tigger repository in $dirName"