#! /bin/dash

# ==============================================================================
# tigger-init.sh
# Implementation of tigger-init command.
#
# Initialise .tigger repository .tigger
#
# Written by: Kristine Jin <z5362038@ad.unsw.edu.au>
# Date: 8/07/2022
# For COMP2041 Assignment 1
# ==============================================================================

dirName=".tigger"


if [ -d "$dirName" ]
then
    echo "$0: error: $dirName already exists" 1>&2
    exit 1
fi 

initbranch="master"

# create .tigger directory
mkdir $dirName
# create branches directory inside .tigger
mkdir $dirName/branches
# create branches directory inside .tigger
echo "master" > $dirName/branches/branchLog
# create directory for master
mkdir $dirName/branches/$initbranch
# create empty log file in master branch
touch $dirName/branches/$initbranch/log
# create repo for master branch
mkdir $dirName/branches/$initbranch/repo
# create index directory for master branch
mkdir $dirName/branches/$initbranch/index
# set HEAD to master
echo "$initbranch" > $dirName/HEAD
# finish initialisation 
echo "Initialized empty tigger repository in $dirName"